import { useState } from 'react'
import { loadItinerary, exportToJSON, getSettings, calculateDate } from '../utils/storage'

function ExportPage() {
  const [preview, setPreview] = useState('')
  const [format, setFormat] = useState('json')

  const itinerary = loadItinerary()
  const days = itinerary.days || []

  const stats = {
    total: days.length,
    complete: days.filter(d => d.status === 'complete').length,
    reviewed: days.filter(d => d.status === 'reviewed').length
  }

  const handlePreview = () => {
    if (format === 'json') {
      setPreview(exportToJSON())
    } else if (format === 'website') {
      setPreview(generateWebsiteFormat())
    }
  }

  const handleDownload = () => {
    const content = format === 'json' ? exportToJSON() : generateWebsiteFormat()
    const filename = format === 'json' ? 'itinerary.json' : 'itineraryData.js'
    const type = format === 'json' ? 'application/json' : 'application/javascript'

    const blob = new Blob([content], { type })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)
  }

  const generateWebsiteFormat = () => {
    const settings = getSettings()
    const formatted = days.map(day => {
      const calculatedDate = settings.startDate ? calculateDate(day.day, settings.startDate) : day.date
      return {
        day: day.day,
        date: calculatedDate || day.date,
        title: {
          en: day.enhanced.title || day.original.title,
          cn: "" // To be translated
        },
        location: {
          en: day.original.location,
          cn: ""
        },
        region: guessRegion(day.original.location),
        coordinates: [0, 0], // To be filled
        images: day.images || [],
        description: {
          en: day.enhanced.description || day.original.description,
          cn: ""
        },
        highlights: {
          en: day.enhanced.highlights || day.original.highlights,
          cn: []
        },
        meals: {
          en: day.enhanced.meals || day.original.meals,
          cn: ""
        },
        accommodation: {
          en: day.enhanced.accommodation?.name || day.original.accommodation,
          cn: ""
        }
      }
    })

    return `// Generated by Content Manager
// Date: ${new Date().toISOString()}

export const itineraryDays = ${JSON.stringify(formatted, null, 2)};

export default itineraryDays;
`
  }

  const guessRegion = (location) => {
    const loc = (location || '').toLowerCase()
    if (loc.includes("xi'an") || loc.includes('xian')) return 'xian'
    if (loc.includes('beijing')) return 'beijing'
    if (loc.includes('lushan') || loc.includes('jiujiang') || loc.includes('jingdezhen') || loc.includes('wuyuan')) return 'lushan'
    if (loc.includes("tai'an") || loc.includes('taishan') || loc.includes('qufu')) return 'taishan'
    if (loc.includes('qingdao')) return 'qingdao'
    return 'unknown'
  }

  // Show message if no data
  if (days.length === 0) {
    return (
      <div>
        <h1 style={{ marginBottom: '20px' }}>Export Itinerary</h1>
        <div className="card">
          <h2>No Data to Export</h2>
          <p style={{ color: '#666', marginBottom: '15px' }}>
            You need to import an itinerary first before you can export.
          </p>
          <a href="/import">
            <button className="primary">Go to Import</button>
          </a>
        </div>
      </div>
    )
  }

  return (
    <div>
      <h1 style={{ marginBottom: '20px' }}>Export Itinerary</h1>

      {/* Status summary */}
      <div className="card">
        <h2>Export Status</h2>
        <div style={{ display: 'flex', gap: '30px', marginBottom: '15px' }}>
          <div>
            <strong>{stats.total}</strong> Total Days
          </div>
          <div>
            <strong>{stats.complete + stats.reviewed}</strong> Ready for Export
          </div>
          <div>
            <strong>{stats.total - stats.complete - stats.reviewed}</strong> Still in Progress
          </div>
        </div>

        {stats.total - stats.complete - stats.reviewed > 0 && (
          <p style={{ color: '#92400e', background: '#fef3c7', padding: '10px', borderRadius: '6px' }}>
            Some days are still in draft or in-progress. You can still export, but content may be incomplete.
          </p>
        )}
      </div>

      {/* Export options */}
      <div className="card">
        <h2>Export Format</h2>
        <div style={{ display: 'flex', gap: '15px', marginBottom: '15px' }}>
          <label style={{ display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer' }}>
            <input
              type="radio"
              name="format"
              value="json"
              checked={format === 'json'}
              onChange={e => setFormat(e.target.value)}
            />
            <span>JSON (Full data with original/enhanced)</span>
          </label>
          <label style={{ display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer' }}>
            <input
              type="radio"
              name="format"
              value="website"
              checked={format === 'website'}
              onChange={e => setFormat(e.target.value)}
            />
            <span>Website Format (itineraryData.js)</span>
          </label>
        </div>

        <div style={{ display: 'flex', gap: '10px' }}>
          <button className="secondary" onClick={handlePreview}>
            Preview
          </button>
          <button className="primary" onClick={handleDownload}>
            Download {format === 'json' ? 'JSON' : 'JS'}
          </button>
        </div>
      </div>

      {/* Preview */}
      {preview && (
        <div className="card">
          <h2>Preview</h2>
          <pre style={{
            background: '#1a1a2e',
            color: '#e5e5e5',
            padding: '15px',
            borderRadius: '6px',
            overflow: 'auto',
            maxHeight: '400px',
            fontSize: '0.85rem',
            lineHeight: '1.5'
          }}>
            {preview}
          </pre>
        </div>
      )}

      {/* Quick copy */}
      {days.length > 0 && (
        <div className="card">
          <h2>Quick Copy to Clipboard</h2>
          <button
            className="secondary"
            onClick={() => {
              const content = format === 'json' ? exportToJSON() : generateWebsiteFormat()
              navigator.clipboard.writeText(content)
              alert('Copied to clipboard!')
            }}
          >
            Copy {format === 'json' ? 'JSON' : 'JS'} to Clipboard
          </button>
        </div>
      )}
    </div>
  )
}

export default ExportPage
